# Generated by Django 3.2.19 on 2023-06-25 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_rename_task_comment_related_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='related_task',
            new_name='task',
        ),
    ]
