# Generated by Django 3.2.19 on 2023-06-24 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_watching', to=settings.AUTH_USER_MODEL)),
                ('task_watched', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_watched', to='tasks.task')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('owner', 'task_watched')},
            },
        ),
    ]
