# Generated by Django 3.2.19 on 2023-06-06 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0024_task_watchers'),
        ('watchers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watcher',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='watcher',
            name='watching',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_watching', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='watcher',
            name='watched',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_watched', to='tasks.task'),
        ),
        migrations.AlterUniqueTogether(
            name='watcher',
            unique_together={('watching', 'watched')},
        ),
        migrations.RemoveField(
            model_name='watcher',
            name='owner',
        ),
    ]
