# Generated by Django 3.2.19 on 2023-06-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watcher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
