# Generated by Django 3.2.19 on 2023-06-04 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0023_task_owner_comments'),
        ('watchers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watcher',
            options={'ordering': (['task'],)},
        ),
        migrations.AddField(
            model_name='watcher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='watcher',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watcher', to='tasks.task'),
        ),
        migrations.AlterUniqueTogether(
            name='watcher',
            unique_together={('owner', 'task')},
        ),
        migrations.RemoveField(
            model_name='watcher',
            name='comments',
        ),
    ]
