# Generated by Django 3.2.19 on 2023-06-06 14:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_task_watchers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watchers', '0002_auto_20230606_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watcher',
            old_name='watched',
            new_name='task_watched',
        ),
        migrations.RenameField(
            model_name='watcher',
            old_name='watching',
            new_name='user_watching',
        ),
        migrations.AlterUniqueTogether(
            name='watcher',
            unique_together={('user_watching', 'task_watched')},
        ),
    ]
