# Generated by Django 3.2.19 on 2023-06-04 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_task_owner_comments'),
        ('watchers', '0002_auto_20230604_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watcher',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='watcher',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='tasks.task'),
        ),
    ]
