# Generated by Django 3.2.19 on 2023-06-20 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('owner_comments', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, default='../default_post_bge1xm', null=True, upload_to='images/')),
                ('priority', models.CharField(choices=[('PRIORITY1', '1'), ('PRIORITY2', '2'), ('PRIORITY3', '3')], default='PRIORITY1', max_length=25)),
                ('task_status', models.CharField(choices=[('BACKLOG', 'Backlog'), ('TODO', 'To Do'), ('INPROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='BACKLOG', max_length=25)),
                ('category', models.CharField(default='Uncategorised', max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
