# Generated by Django 3.2.19 on 2023-06-21 07:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 21, 7, 44, 54, 798683, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 21, 7, 44, 54, 798648, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 21, 7, 44, 54, 798669, tzinfo=utc)),
        ),
    ]
