# Generated by Django 3.2.19 on 2023-06-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20230615_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.FileField(blank=True, default='../default_post_bge1xm', upload_to='images/'),
        ),
    ]
