# Generated by Django 3.2.19 on 2023-06-04 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='comments',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='task',
            name='content',
        ),
    ]
