# Generated by Django 3.2.19 on 2023-06-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='attachments',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
