# Generated by Django 3.2.19 on 2023-06-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('Backlog', 'BACKLOG'), ('To Do', 'TODO'), ('In Progress', 'INPROGRESS'), ('Completed', 'COMPLETED')], default='BACKLOG', max_length=25),
        ),
    ]
