# Generated by Django 3.2.19 on 2023-06-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20230625_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed_date',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
