# Generated by Django 3.2.19 on 2023-06-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('1', 'PRIORITY1'), ('2', 'PRIORITY2'), ('3', 'PRIORITY3')], default='PRIORITY1', max_length=25),
        ),
    ]
