# Generated by Django 3.2.19 on 2023-06-16 18:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='attachments',
            field=models.FileField(blank=True, upload_to='files/', validators=[django.core.validators.FileExtensionValidator(['.pdf', '.doc', '.docx', '.ppt', '.pptx', '.xls', '.xlsx', '.txt', 'pdf', 'doc', 'docx', 'ppt', 'pptx', 'xls', 'xlsx', 'txt'])]),
        ),
    ]
