# Generated by Django 3.2.19 on 2023-06-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_task_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.FileField(blank=True, default='../default_post_bge1xm', null=True, upload_to='images/'),
        ),
    ]
