# Generated by Django 3.2.19 on 2023-06-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='updated_date',
            field=models.DateField(null=True),
        ),
    ]
