# Generated by Django 3.2.19 on 2023-06-04 10:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_task_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='updated_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
