# Generated by Django 3.2.19 on 2023-06-23 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20230622_0618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='notes',
            new_name='description',
        ),
    ]
