# Generated by Django 3.2.19 on 2023-06-24 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_rename_notes_task_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('related_tasks', models.ManyToManyField(blank=True, related_name='categories', to='tasks.Task')),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, default='Uncategorised', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='tasks.category'),
        ),
    ]
