# Generated by Django 3.2.19 on 2023-06-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_task_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('BACKLOG', 'Backlog'), ('TODO', 'To Do'), ('INPROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='BACKLOG', max_length=25),
        ),
    ]
