# Generated by Django 3.2.19 on 2023-06-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_task_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('1', 'PRIORITY1'), ('2', 'PRIORITY2'), ('3', 'PRIORITY3')], default='PRIORITY1', max_length=25),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('Backlog', 'BACKLOG'), ('To Do', 'TODO'), ('In Progress', 'INPROGRESS'), ('Completed', 'COMPLETED')], default='BACKLOG', max_length=25),
        ),
    ]
