# Generated by Django 3.2.19 on 2023-06-24 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_auto_20230624_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='related_tasks',
            field=models.ManyToManyField(blank=True, default='', related_name='categories', to='tasks.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='tasks.category'),
        ),
    ]
