# Generated by Django 3.2.19 on 2023-06-04 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_auto_20230604_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='datetime_field',
        ),
    ]
