# Generated by Django 3.2.19 on 2023-06-04 11:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_remove_task_datetime_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='datetime_field',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
