# Generated by Django 3.2.19 on 2023-06-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_alter_category_related_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='related_tasks',
            field=models.ManyToManyField(blank=True, related_name='categories', to='tasks.Task'),
        ),
    ]
