# Generated by Django 3.2.19 on 2023-06-04 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_task_datetime_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='datetime_field',
        ),
    ]
