# Generated by Django 3.2.19 on 2023-06-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_alter_task_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='owner_comments',
            field=models.TextField(blank=True),
        ),
    ]
