# Generated by Django 3.2.19 on 2023-06-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchers', '0001_initial'),
        ('tasks', '0023_task_owner_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='watchers',
            field=models.ManyToManyField(to='watchers.Watcher'),
        ),
    ]
