# Generated by Django 3.2.19 on 2023-06-06 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_task_watchers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='watchers',
        ),
    ]
