# Generated by Django 3.2.19 on 2023-06-10 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchers', '0004_auto_20230606_1513'),
        ('tasks', '0025_remove_task_watchers'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='watcher',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='watchers.watcher'),
        ),
    ]
