# Generated by Django 3.2.19 on 2023-06-10 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0026_task_watcher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='watcher',
            new_name='watcher_id',
        ),
    ]
