# Generated by Django 3.2.19 on 2023-06-10 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchers', '0004_auto_20230606_1513'),
        ('tasks', '0029_alter_task_watcher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='watcher_id',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='watchers.watcher'),
        ),
    ]
