# Generated by Django 3.2.19 on 2023-06-10 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0034_alter_task_watcher_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='watcher_id',
        ),
    ]
