# Generated by Django 3.2.19 on 2023-06-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0035_remove_task_watcher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='owner_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
